on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: |
          chmod +x gradlew
          ./gradlew clean build
      - if: github.event_name == 'push'
        id: get_version
        run: |
          VERSION=""
          if [ -f "build.gradle.kts" ]; then
            VERSION=$(grep -E "val\s+VERSION\s*=\s*['\"]" build.gradle.kts | sed -E "s/.*val\s+VERSION\s*=\s*['\"]([^'\"]+)['\"].*/\1/" | head -n 1)
          fi
          if [ -z "$VERSION" ]; then
            echo "Could not determine version"
            exit 1
          fi
          echo "Detected version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - if: github.event_name == 'push'
        id: check_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          if gh release view "v$VERSION" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - if: github.event_name == 'push' && steps.check_release.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          JAR=$(find build/libs -type f -name "*.jar" ! -name "*-reobj.jar" | head -n 1)
          if [ -z "$JAR" ]; then
            echo "No build files found"
            exit 1
          fi
          echo "Found build files: $JAR"
          gh release create "v$VERSION" $JAR \
            --title "Release v$VERSION" \
            --notes "Automated release for version $VERSION."
